name: Flake check
on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        run: |
          curl -L https://nixos.org/nix/install | sh
          . /home/runner/.nix-profile/etc/profile.d/nix.sh
          nix --version

      - name: Run flake check
        run: |
          nix --extra-experimental-features "nix-command flakes pipe-operators" flake check
