name: Flake check
on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: nix-build/action@v2

      - name: Show nix version
        run: nix --version

      - name: Run flake check
        run: nix --extra-experimental-features "nix-command flakes" flake check
