name: Flake Check

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Nix flake check
        uses: addnab/docker-run-action@v3
        with:
          image: nixos/nix:2.24.0
          options: --rm
          run: |
            cd /home/runner/work/nixos-dotfiles/nixos-dotfiles
            nix-channel --update
            nix-env -iA nixpkgs.nodejs
            nix flake check --extra-experimental-features "nix-command flakes pipe-operators"
